### ISSUE TITLE
Custom toolchain for R

### ISSUE THREAD

**Issue by siddharthab** [grailbio/rules_r#1]
We rely on system provided R and are not controlling the version of R being used, or the packages installed at `.Library` search path.

A toolchain to have better control will make the build more hermetic.

**Comment by siddharthab** [comment]
Some extra information in [this thread](https://groups.google.com/d/msg/bazel-discuss/7B0FaU5Pkmo/jg0_EReqAQAJ).

**Comment by hchauvin** [comment]
Did you make any progress on this one?

I suppose a first step would be to define a toolchain with a `configure` script that gets the local version of R (as does local_jdk or local_cc).  I don't know about, e.g., building R from source as R depends on so many things, even though I guess this could be the next step.

(I'm asking because it would be a nice-to-have for my migrating to R 3.5.0.)

**Comment by siddharthab** [comment]
I have not worked on this, and unfortunately won't have the time to work on it.

Simply having a version enforcement is not enough because what if the user wants another version installed on their machine for their adhoc development work.

On macOS, you can [maintain multiple versions](https://cran.r-project.org/doc/manuals/r-release/R-admin.html#Multiple-versions) easily, and you can ask the user to install the version you want in addition to the one they want. You can just as easily use a homebrew bottle and install it yourself in a bazel repository.

But I don't know how to guide the user to setup multiple versions of R on linux, or do it ourselves. The only solution could be to build from source. But we will have to be very strict about the cache not getting invalidated.

If this is important to you, I won't mind if you take this up.

**Comment by hchauvin** [comment]
So I did some geeking on toolchains, and it turns out that setting up a proper toolchain system for R is not a trivial endeavor.  I have a version that sort of works for my use case, but I think it would be useful to look at the big picture and discuss what a proper design should be.

In my opinion, a toolchain should come with the following properties:
- It should be possible to do, e.g., `brew install bazel && git clone ... && bazel build //...` without worrying about system dependencies.
- It should be possible to juggle between a "local," system version of R maintained by a package manager such as Homebrew or Apt, and a "standalone" version of R, maintained by Bazel. The standalone version should be fully hermetic.
- There should be a complete continuity between the development environment and the production, Dockerized environment.  Right now, one needs to pick the exact Linux distribution for the base Docker image and the development machine.

(The underlying themes are ease of configuration and reproducibility.)

I don't think it is a good idea, after all, to install R from source.  I've experimented with replacing the Makefile-based build system for R with BUILD files, but the process relies too much on the internals of R and is neither backward nor forward compatible. I've also considered doing `./configure && make && make install` in a repository rule (repository rules are where to put all the non-hermetic stuff, and invoking `make` there is something people do), but the compilation time from scratch of around 20 min is offputting.

However, I feel confident reaching for the distributed binaries for R, both on Mac OSX and Ubuntu, and I can go back as far as 3.1.0 with this system (which is a sign that the whole process is stable).

The way I do so currently is I pull the archives in a repository_rule and extract them into the repository.  I could have used a BUILD rule instead, but this would have prevented me from using a non-system R installation for razel.

I then patch some hardcoded paths very lightly (in 2 places for Linux, 3 places for Mac OSX) so that everything points to the R_HOME environment variable, and is thus relative (and within the execroot).  R_HOME is set through a wrapper script from, e.g., the RUNFILES root.

On Mac OSX, the binary distribution is self-contained, and I don't have to download anything else.  On Ubuntu, the binary distributions depend on a myriad of packages, mostly pulled because of Cairo (used for graphics rendering). Having experience with [distroless Docker images](https://github.com/GoogleContainerTools/distroless), I resolved to put the required *.deb packages in the execroot. The list of deb packages is hardcoded in a *.bzl file and generated by a utility that pulls all the transitive dependencies of r-base-core in a Docker container.

So all this might sound extremely contorted, but in the end, it allows this:
- it is possible to pin down an exact version of R in the workspace, then decide to either check the local version (or versions in the case of Mac OSX) or simply download it.
- The whole thing is standalone, and it is verifiable by excluding some paths in sandbox mode. It is also completely pinned down with digests. Meaning: no need to install R outside of Bazel and the builds, apart from the stamping, are fully reproducible.
- As a bonus, on Linux, the standalone installation of R can be used directly in a Docker layer and slapped onto an Ubuntu image to give a base R image.

What are your thoughts on that?

**Comment by siddharthab** [comment]
Hadrien, thank you for working on this. I understand this is a significant endeavor because R on linux does not come in a neat self-contained distribution.

On linux, how are you using the docker image to do your R builds and tests?

bazel is coming up with a docker sandbox feature in its next release. I tested it last week that it will work with rules_r. I still have to figure out how to make it work with rules_go though, so I can not quite use it yet.

**Comment by siddharthab** [comment]
Ah I misread your setup. You extract the .deb files out of the docker container and hardcode them in a .bzl file. This is OK. But how do you unpack the .deb files? My naive understanding is that .deb packages can not be installed in other prefixes.

**Comment by hchauvin** [comment]
Yes, sorry, the Docker container part is a bit misleading.  Here is what I do to get a list of Debian packages that would be installed transitively:
```
docker run --rm -i "$DOCKER_IMAGE" /bin/bash <<EOF
apt-get update >/dev/null
apt-get -q -y install --no-install-recommends --no-install-suggests --print-uris $PACKAGES | cut -f 2 -d \' | grep "\.deb"
exit
EOF
```

This allows basically to get everything that is not in the base Linux distribution (with `DOCKER_IMAGE` being, e.g., `"ubuntu:trusty"`).  Concerning the extraction: a .deb file is an archive of three files. One of these files is itself an archive and it contains all the files to copy, relative to '/', so you can extract them in a custom location by doing `ar ... | tar -xf ... -C ...`.

***

Anyway, as I said this is a massive endeavor, and there are many design decisions along the way, and I'm not sure what I explained above is the right way. Again, it works for me, but it might not be generalizable. For instance, a Docker spawn strategy is coming in Bazel, as you remarked, and I'm not sure of the implications of that.

I put what I feel is the least controversial part in #27. It clarifies the relationship of rules_r with system R, especially with respect to versioning, and is probably more than enough for now.

**Comment by hchauvin** [comment]
I put 1. and 2. in a commit. You might think by looking at the CI duration that there is some serious performance hit, but actually it's because I'm running the tests twice, once to test the actual toolchain, once with a strongly sandboxed toolchain to check that everything runs through the toolchain and not goes directly to system R.

**Comment by hchauvin** [comment]
I just put another, experimental piece of feature to execute all Bazel actions in a Docker container using `--spawn_strategy=docker`.  The trick is to define correctly the crosstool_top, to use a Remote Bazel Execution image with R installed and to define the proper R toolchain (it might be a silly question by the way, but have you tried rules_go with the crosstool_top I use in the commit?).

This cannot be tested on travis because it relies on a not-yet-released feature, but this is definitely something I need. The example I give is basically a cheap remote execution worker that can work on a local workstation, and it would allow my collaborators and myself to not have to rely on a Linux box on the side, which is actually the biggest pain point.

**Comment by hchauvin** [comment]
Another interesting feature of a standalone toolchain (one that does not rely at all on system R) is that if no dependency to build depends on Fortran, r_binary_image can be put within bazelbuild/docker without having to change their build system. But again, apart from that I'm still pondering the usefulness of a standalone toolchain.

**Comment by siddharthab** [comment]
Thank you for continuing to work on this! And I am glad that the docker sandbox strategy is working for you. The entire toolchain can be defined by repository rules so razel should not be a problem. On a first glance, the overall design looks good to me, but I still need to do a thorough review of the code. I will retain the core ideas but I might change the interface.

You can continue working on your branch for your use cases and I will start picking up your work, clean it, and push it through our internal system. As time permits.

In general, I like how rules_go handles toolchains, and will keep the interface similar to theirs. Although I might not use the cpp configuration fragment that they use to determine components of the cc toolchain, and will rely on users to supply their own. For example, https://github.com/siddharthab/bazel-toolchain/blob/master/toolchain/Makevars.tpl

**Comment by hchauvin** [comment]
Hi Siddhartha,

Thanks for putting the time to review this! https://github.com/grailbio/bazel-toolchain is indeed a nice way to make LLVM hermetic.  In this PR, I put the logic as an extra toolchain instead of a crosstool, but it's basically the same and I also use a Makevars instead of relying on the cpp configuration fragment.

To follow up on design, another reason to define a proper toolchain is to ensure that the cache remains consistent by tying the actions to the toolchain, see https://github.com/bazelbuild/bazel/issues/4558. So that's why it is crucial to discover the version of R, even for a local toolchain.

As you mention rules_go, here the runtime is not provided as Go depends on a few system libraries that are available practically everywhere (https://github.com/GoogleContainerTools/distroless/tree/master/base).  However, for R, you have the whole of `libcairo` to add if you want graphics.  Maybe the best is to allow, as for the python rules, both system and "standalone" runtimes.  That's why I've included a way to specify the runfiles of the R and Rscript executables, to allow for going in this direction.

Concerning the runtime, I was also thinking about including R in `rules_docker` and `distroless`.  However, I think the problem here is that, contrary to all of the other languages there, R is not general purpose and has different needs, so maybe it makes sense to keep it isolated and have the container rules here.  In the same vein, it probably also makes sense to have a "distroless" container layer for R in this same repo.  That would go towards providing the runtime in a nice way.

* * *

Although it is not strictly related to toolchain support, I've also added a commit to remove the reliance on `ctx.declare_directory` for the "lib" directory, because it messes with remote execution: with https://github.com/bazelbuild/bazel/blob/c6cf1b94ea0753bb1cc7d0df8c5a8a2762a53eab/src/tools/remote/src/main/java/com/google/devtools/build/remote/worker/ExecutionServer.java#L198, if you do `bazel build //... --remote_executor=localhost:8080 --spawn_strategy=remote --crosstool_top=@bazel_toolchains//configs/debian8_clang/0.3.0/bazel_0.13.0/default:toolchain --cpu=k8 --host_cpu=k8`, you get the remote error:
```
java.nio.file.FileAlreadyExistsException: Output directory/file already exists: /tmp/workpath/build-218da7d3-8424-4073-8eb3-18b185bfce8a/bazel-out/k8-fastbuild/bin/external/R_praise/lib
    at com.google.devtools.build.remote.worker.ExecutionServer.execute(ExecutionServer.java:199)
    at com.google.devtools.build.remote.worker.ExecutionServer.execute(ExecutionServer.java:153)
    at com.google.devtools.build.remote.worker.ExecutionServer.lambda$execute$0(ExecutionServer.java:135)
    at io.grpc.Context$2.call(Context.java:602)
    at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
    at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
    at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```

Now, when I implemented this in Bazel, I chose to disallow writing files within declared directories, because this nesting would mean that you cache (and so upload/download) each file in the tree twice: once as part of the declared directory, once as an individual file.  Local execution of Bazel is more lenient, but I don't think this leniency is warranted, and anyway this behavior is kind of implicit in the way the [remote execution interface](https://github.com/googleapis/googleapis/blob/master/google/devtools/remoteexecution/v1test/remote_execution.proto) was written.

Also, there is currently no directory support for the `buildfarm` project, although there is https://github.com/bazelbuild/bazel-buildfarm/pull/128 in progress, and it should probably converge to the implementation in https://github.com/bazelbuild/bazel, with the deliberate limitations above.

**Comment by siddharthab** [comment]
Thank you Hadrien. Your points understood about the complex runtime demanded by R and the problem with declared directories for remote execution.

I will start giving some thought to this soon. Maybe the linux solution would be to use a docker sandbox. We can also provide users the option to compile a certain version of R if they so want. In any case, we can definitely put the local installation version check.

**Comment by siddharthab** [comment]
I have removed all declared files and am only keeping the declared directory. I did not know that directories are listed recursively. But your comments here made me look into it more and I was able to simplify the code base significantly. Thank you!

**Comment by hchauvin** [comment]
Glad you were able to do that. I went in my proposal in the opposite direction and only kept the declared files, because I think it is more explicit, but yours make more sense because it’s probably faster and avoids compatibility problems such as when switching to R 3.5.0 and encountering a cryptic error actually caused by a missing file.

Now it means that I should follow more closely how directory outputs are implemented in bazel-buildfarm, because this is part of my setup and right now incompatible with directories.

Did you find a solution for go BTW?

**Comment by siddharthab** [comment]
What do you mean by solution for go?

**Comment by hchauvin** [comment]
Sorry you got it too fast :p I needed to switch from my phone to my computer to get the reference.

I mean using the remote or spawn strategy with go rules.  Just to let you know that I can "fake" cross-compile a go target for Linux by passing `--platforms=@io_bazel_rules_go//go/toolchain:linux_amd64` as a Bazel build option.  One thing to note through is that the spawning strategy is used only for `bazel build` and `bazel test`, not for `bazel run`.  So if you do `bazel run //some:go_target --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 --spawn_strategy=remote ...` you won't be running the target remotely and it will fail.

**Comment by siddharthab** [comment]
I have not tried it. Using --platforms is not enough, because rules_go uses select clauses to choose dependencies for a go library but select clauses are only activated by the --cpu flag. I tried it once with the docker sandbox thing from my mac, but the compilation for stdlib was not following crosstool_top. It would have worked from Linux though. Probably some work needs to go in there.

bazel run was designed to run things locally. You should not perform non-hermetic operations on a shared infrastructure.

**Comment by hchauvin** [comment]
I mean I suspected that that was the reason for bazel run, but you still can have use cases where you have an executable that runs only on linux but performs legit, hermetic operations. Anyway that's an implementation choice that is perfectly understandable.

Concerning --platforms, I can confirm that doing on Mac OSX
```
bazel run //:some_docker_image \
  --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64
```
where some_docker_image is a container_image rule that has a Go program as an entrypoint loads a docker image in the local Docker daemon with an executable in the right format.  If your Go program have C/C++ dependencies, I think that adding --cpu=, --host_cpu=, --crosstool_top= should be enough to compile those dependencies for the right platform, but I've not tried it in the context of a go rule.

I've also not tried with the docker spawn strategy, but it might be enough to specify the right cross compiler on top of that.

**Comment by hchauvin** [comment]
```
bazel test \
  --spawn_strategy=docker --genrule_strategy=docker \
  --define=EXECUTOR=remote \
  --experimental_docker_image=... \
  --cpu=k8 --host_cpu=k8 --crosstool_top=... \
  --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 \
  --host_platform=@io_bazel_rules_go//go/toolchain:linux_amd64 //foo:bar_test
```

should do the trick without cgo once https://github.com/bazelbuild/rules_go/issues/1507 is resolved.
For cgo, it seems that there is some additional work to do.

**Comment by siddharthab** [comment]
Closed through the following commits:
00fc9df6db0a09d453ed8ab21eb3882ffaf2db58
d9d6f94b882a62b412054b1839719d814e425b0a
aef175e22d6e621cf50cebd839ac49ab8d8ac9dc
1a16933f1ee7c287eddd7661523f567a09862a0b
fbcde367b4e9a37c69ec7b2ca60b7566eda5153f
b7077a90da04266be38768826ffab1692685011f
