### ISSUE TITLE
Code coverage

### ISSUE THREAD

**Issue by hchauvin** [grailbio/rules_r#22]
It would be possible to get code coverage for r_pkg as follows:
- The covr R package could be used for a mix of offline and online instrumentation: the package loader script would be modified offline to instrument the package when it is loaded.  Some covr internals have to be used here, but thanks to rules_r it is possible to pin down a compatible version.
- A small function in R converts the covr line-by-line format to an LCOV coverage report.
- The LCOV coverage reports are collected by Bazel into bazel-testlogs when testing with 'bazel coverage'.

It is possible to wrap an r_binary invocation in a similar way.

The LCOV reports can then be consumed in many ways, for instance using the genhtml command-line utility.

Code coverage can be transitive if --instrumentation_filter is properly set, and covr integrates nicely with native code, either generated by rules_r or handled through cc_deps.

**Comment by siddharthab** [comment]
It's a great idea, and thank you for coming up with a rough outline.

I do not have in-depth knowledge about how covr or how bazel's coverage collection mechanism works, and I won't have the bandwidth to do any additional work on rules_r for the next few months. My only thought is that we should not fold in too much complexity from non-base packages into r_pkg. I was reluctant even for roclets, but I could isolate the dependency there for only when needed by the user.

A few preliminary thoughts. We can't expect people to modify the loader, that needs to be as light weight as possible. It looks like any coverage work is more suited for r_unit_test or r_pkg_test rules, rather than r_pkg. What if it was a test script living in the tests/ directory (we can also insert it ourselves as an option, but I would prefer people doing it because then they control the details of how they invoke covr). People specify 'covr' as a suggested_dep, and there is an attribute in the test rules telling bazel to collect and process the coverage report after the tests are run. I think this will be more straightforward with r_unit_test than with r_pkg_test, so it's OK to leave the latter out.

If you want to take a stab at it, we can get it into this project. You don't have to worry about getting coverage for cc_deps correctly at first iteration.

Also be aware that coverage collection does not fully work yet in open-source bazel -- https://github.com/bazelbuild/bazel/issues/1118 -- not sure which parts are missing.

**Comment by hchauvin** [comment]
Hi Siddhartha, thanks for the support.

Concerning the loader, this is the way covr currently works.  What it does is it highjacks package loading and instruments the code on the flight.  Maybe there is a better way, but I can't think of any.

In Bazel, coverage is controlled both by ctx.configuration.coverage_enabled, which tells whether code coverage is enabled for this bazel run (that is, bazel coverage was invoked instead of bazel test), and ctx.coverage_instrumented(), which tells whether the current rule should be instrumented.  This way, and I forgot to mention that, both r_unit_test and r_pkg have to be involved:
- r_unit_test collects coverage info
- r_pkg is used for offline instrumentation (and offline instrumentation proceeds only if ctx.coverage_instrumented() is True).

This is the way code coverage works for, e.g., the Java rules.  As for cc_deps, this part is already more or less taken care of by Bazel which specifies the --coverage option to the compiler, and there is already a mechanism in covr to gather the gcda/gcno coverage files.

Concerning the parts missing in Bazel, the only thing I can think of that truly matters is that there is no way to gather multiple coverage data files generated in one run (because the LcovMerger tool is currently a stub, but that's simple to change).  In practice, it only means that forking or spawning a new process that is also instrumented won't work.

**Comment by siddharthab** [comment]
Closed through 6ba61f01cf8a29a4c9a9aa4eaacf86c611cddabb. There is no future work planned on this feature right now. I will track the evolution of coverage collection on bazel and will keep our implementation here up to date.
